# Zombie Tag Config
# By Jamplifier

PlayerNeeded: 2
MaxPlayers: 20
GameLength: 300 # Game length in seconds (5 minutes)
AnnounceGameLength: true
GracePeriod: 10 # Seconds during which zombies cannot tag
ZombieSpeedBoost: true # Zombies get a speed boost

SurvivorReward:
  Enabled: true
  Command: "give {player} golden_apple 2" # Console command to run for survivors

HeadItem:
  Type: ZOMBIE_HEAD # Configurable item placed on zombies' heads

Messages:
  ZombieWin: "§cZombies win! All players have been tagged."
  SurvivorWin: "§aSurvivors win! You escaped the zombie apocalypse!"

LobbySpawn:
  world: world
  X: 0
  Y: 0
  Z: 0

GameSpawn:
  world: world
  X: 0
  Y: 0
  Z: 0
  
  
