# Zombie Tag Config
# By Jamplifier

# Game settings
PlayerNeeded: 2               # Minimum players needed to start the game
MaxPlayers: 20                # Maximum number of players in the game
GameLength: 300               # Game length in seconds (5 minutes)
AnnounceGameLength: true      # Announce game length at the start
GracePeriod: 10               # Seconds during which zombies cannot tag
# Survivor rewards
SurvivorReward:
  Enabled: true               # Enable or disable survivor rewards
  Command: "give {player} golden_apple 2" # Console command to run for survivors

# Head item for zombies
HeadItem:
  Type: ZOMBIE_HEAD           # Configurable item placed on zombies' heads

# Messages
Messages:
  ZombieWin: "§cZombies win! All players have been tagged."
  SurvivorWin: "§aSurvivors win! You escaped the zombie apocalypse!"

# Spawn locations
LobbySpawn:
  world: world
  X: 0
  Y: 0
  Z: 0

GameSpawn:
  world: world
  X: 0
  Y: 0
  Z: 0

# Effects settings
Effects:
  BlindnessDuration: 10        # Duration of blindness effect in seconds
  NightVisionDuration: 10      # Duration of night vision effect in seconds

# Stay Still Timer settings
StayStillTimer:
  Enabled: true               # Enable or disable the stay-still timer
  TimeLimit: 10               # Time in seconds before a stationary player is turned into a zombie
  Message: "§cYou stayed still for too long and turned into a zombie!"

