name: ZombieTag
version: 1.2
main: com.jamplifier.MainClass
api-version: 1.21
description: A Zombie Tag plugin for FriendlySMP
commands:
  zombietag:
    description: ZombieTag plugin commands
    usage: /zombietag <help|join|leave|setspawn|teleport|reload>
    permission: zombietag.player
    permission-message: You do not have permission to use this command!
permissions:
  zombietag.player:
    description: Allows access to basic ZombieTag commands (join, leave, help)
    default: true
  zombietag.admin:
    description: Allows access to admin commands for ZombieTag (reload, setspawn, teleport)
    default: op
