# Zombie Tag — Config v2
# Keep "version" so you can migrate safely later.
version: 2

lobby:
  player_needed: 2              # min players to start
  max_players: 20               # cap in lobby
  countdown_seconds: 10         # countdown once threshold met
  auto_rejoin: true             # queue players who join during an active round
  queue_during_game: true

game:
  length_seconds: 300           # total round time
  grace_seconds: 10             # zombies can’t tag during this window
  announce_length: true         # say game length at start

rewards:
  survivors:
    enabled: true
    command: "give {player} golden_apple 2"  # runs as console

items:
  zombie_helmet: ZOMBIE_HEAD    # item type placed on zombies’ heads

messages:
  zombie_win: "§cZombies win! All players have been infected."
  survivor_win: "§aSurvivors win! You escaped the zombie apocalypse!"

spawns:
  lobby:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  game:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0

effects:
  blindness_seconds: 10
  night_vision_seconds: 10

stay_still:
  enabled: true
  time_limit_seconds: 10
  message: "§cYou stayed still for too long and turned into a zombie!"

restrictions:
  block_enderpearls: true
  block_chorus_fruit: true
  block_elytra: true

commands:
  whitelist:
    - "/zombietag"
    - "/zt"
    - "/msg"
    - "/tell"    
	
start_commands:
  - "undisguise %player%"
  - "cosmetics disable %player%"

    
