name: ZombieTag
version: 2.0
main: com.jamplifier.zombietag.MainClass
api-version: 1.21
description: A Zombie Tag plugin for FriendlySMP
softdepend: [PlaceholderAPI]

commands:
  zombietag:
    description: ZombieTag plugin commands
    usage: "/zombietag help"
    aliases: [zt]                    
    permission: zombietag.player
    permission-message: You do not have permission to use this command!

permissions:
  zombietag.player:
    description: Access to basic ZombieTag commands (help, join, leave, top, stats)
    default: true

  zombietag.admin:
    description: Admin commands (reload, setspawn, teleport, info)
    default: op
